# Ejercicios 

**1. Función para Leer archivo y retornar una lista con las palabras que tengan más de 2 caracteres**

In [1]:
def leerArchivo(nombreArch):
    f = open(nombreArch,'r',encoding='utf-8')
    lineas = f.readlines()
    f.close()
    newList = []
    for linea in lineas:
        newArray = []
        for i in linea.split():
            if len(i)>2:
                #print(i)
                newArray.append(i)
        newList.append(" ".join(newArray))
    return newList

In [2]:
lineas = leerArchivo('Eclesiastes1.txt')

In [3]:
lineas

['Todo vanidad',
 '',
 'Palabras del Predicador, hijo David, rey Jerusalén.',
 '',
 'Vanidad vanidades, dijo Predicador; vanidad vanidades, todo vanidad.',
 '',
 '¿Qué provecho tiene hombre todo trabajo con que afana debajo del sol?',
 '',
 'Generación va, generación viene; mas tierra siempre permanece.',
 '',
 'Sale sol, pone sol, apresura volver lugar donde levanta.',
 '',
 'viento tira hacia sur, rodea norte; girando continuo, sus giros vuelve viento nuevo.',
 '',
 'Los ríos todos van mar, mar llena; lugar donde los ríos vinieron, allí vuelven para correr nuevo.',
 '',
 'Todas las cosas son fatigosas más que hombre puede expresar; nunca sacia ojo ver, oído oír.',
 '',
 '¿Qué que fue? mismo que será. ¿Qué que sido hecho? mismo que hará; nada hay nuevo debajo del sol.',
 '',
 '¿Hay algo que puede decir: aquí esto nuevo? fue los siglos que nos han precedido.',
 '',
 'hay memoria que precedió, tampoco que sucederá habrá memoria los que serán después.']

**2. Implementar una función recursiva para generar la secuencia de Fibbonaci**

Fibonacci: Funcion Recursiva

In [4]:
def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n-2) + fibonacci(n-1)    

In [6]:
fibonacci(20)

6765

Fibonacci: Funcion Normal

In [7]:
def fibonacci(n):
    a = 0
    b = 1
    for i in range(n+1):
        r = 0
        if i == 0:
            r = a
        elif i == 1:
            r = b
        else:
            c = a + b
            a = b
            b = c
            r = c
    return r

In [8]:
fibonacci(20)

6765

**3. Crear un directorio con el nombre IA, y generar 50 carpetas dentro de ese directorio con los** **nombres 1, 2, 3, 4,...,50. Para cada carpeta creada, crear un archivo (TXT) dentro de la carpeta**
**con el nombre de la misma carpeta.**
**El archivo debe contener la frase:**
**"Inteligencia ArtificialAvanzada " + nombre del archivo:"Inteligencia Artificial Avanzada 1"**

In [9]:
import os

In [29]:
name1 = os.getcwd()
os.mkdir("IA")
os.chdir('IA')#accede
name2 = os.getcwd()#guarda dir actual
for i in range(50):
    os.mkdir(str(i+1))#crea
    os.chdir(str(i+1))#accede
    a = open(str(i+1)+".txt",'w')#crea archivo txt
    a.write("Inteligencia Artificial Avanzada " + str(i+1))
    a.close()
    os.chdir(name2)#regresa a carpeta IA
os.chdir(name1)#regresa a la carpeta de trabajo principal

In [30]:
name1 = os.getcwd()#verificamos direccion actual
name1

'C:\\Users\\noy-4\\Desktop\\IA\\InteligenciaArtificial\\Tareas\\PrimerTarea'

In [62]:
d = open("IA/50/50.txt",'r')#verificamos archivos creados
print(d.readlines())
d.close()

['Inteligencia Artificial Avanzada 50']


**4. Realizar una función que reciba un matriz (numpy), y las posiciones  X,Y. 
Retornar una submatriz de esa matriz en función a las posiciones**

In [48]:
import numpy as np

In [49]:
def submatriz(M,X,Y):#funcion que retorna submatriz
    return M[X:,Y:]

In [51]:
R = np.random.rand(4,4)#generamos matriz
R

array([[0.02984115, 0.15712801, 0.77211572, 0.84647882],
       [0.95465139, 0.17597816, 0.6787779 , 0.70114804],
       [0.41355932, 0.76719666, 0.13519887, 0.61530698],
       [0.51584443, 0.56005989, 0.61201868, 0.91623329]])

In [52]:
submatriz(R,0,2)#llamamos funcion

array([[0.77211572, 0.84647882],
       [0.6787779 , 0.70114804],
       [0.13519887, 0.61530698],
       [0.61201868, 0.91623329]])

In [55]:
R[0:,2:]#comprobamos

array([[0.77211572, 0.84647882],
       [0.6787779 , 0.70114804],
       [0.13519887, 0.61530698],
       [0.61201868, 0.91623329]])