## OS

In [55]:
import os

In [56]:
os.getcwd()

'C:\\Users\\laboratorioesan\\Desktop\\InteligenciaArtificial'

In [57]:
os.listdir()#archivos de directorio actual

['.git',
 '.ipynb_checkpoints',
 'archivo.txt',
 'IntroduccionJupyter.ipynb',
 'Librerias.ipynb',
 'miarchivo.txt',
 'noticia.txt',
 'PPTS',
 'README.md']

In [58]:
os.listdir(".")#archivos de directorio actual

['.git',
 '.ipynb_checkpoints',
 'archivo.txt',
 'IntroduccionJupyter.ipynb',
 'Librerias.ipynb',
 'miarchivo.txt',
 'noticia.txt',
 'PPTS',
 'README.md']

In [59]:
os.listdir("..\\..")#archivos de directorio C

['.anaconda',
 '.bash_history',
 '.conda',
 '.condarc',
 '.dnx',
 '.FlashPrint',
 '.freemind',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.spss',
 '.VirtualBox',
 '.vscode',
 '3D Objects',
 'AppData',
 'Application Data',
 'Configuración local',
 'Contacts',
 'Cookies',
 'Datos de programa',
 'Desktop',
 'Documents',
 'Downloads',
 'Entorno de red',
 'Favorites',
 'IA_2019-1',
 'IA_AVANZADA',
 'Impresoras',
 'Links',
 'Menú Inicio',
 'MicrosoftEdgeBackups',
 'Mis documentos',
 'Music',
 'My Things',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{8ebe95f7-3dcb-11e8-a9d9-7cfe90913f50}.TM.blf',
 'NTUSER.DAT{8ebe95f7-3dcb-11e8-a9d9-7cfe90913f50}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{8ebe95f7-3dcb-11e8-a9d9-7cfe90913f50}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'ntuser.pol',
 'OneDrive',
 'Pictures',
 'Plantillas',
 'Reciente',
 'Saved Games',
 'Searches',
 'SendTo',
 'Videos',
 'Zotero']

In [60]:
os.listdir("D:")#archivos de directorio D

['$RECYCLE.BIN',
 'Arena',
 'conferencia.7z',
 'G Data',
 'InteligenciaArtificial',
 'io2',
 'Maquinas Virtuales',
 'P4',
 'Pc4',
 'pie',
 'Soft Screen Recorder 8.0.1 [Portable]',
 'System Volume Information']

In [63]:
os.mkdir("Test") #crear carpeta

FileExistsError: [WinError 183] No se puede crear un archivo que ya existe: 'Test'

In [66]:
os.rmdir("Test") #eliminar carpeta

FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado: 'Test'

In [67]:
os.remove("nombreArchivo.txt")

FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado: 'nombreArchivo.txt'

**Ejercicios**
3. Crear un directorio con el nombre IA, y genrar 50 carpetas dentro de ese directorio con los nombres 1,2,3...,50. Para cada carpeta creada, crear un archivo txt dentro de la carpeta con los nombres de la misma carpeta. El archivo debe contener la frase:"inteligencia artificial" + nombre archivo.

## Numpy

In [2]:
import numpy as np #libreria de funciones matemáticas

In [7]:
import time # tiempo

In [4]:
time.sleep(20) #procesa 20 segundos

In [6]:
time.localtime() 

time.struct_time(tm_year=2019, tm_mon=4, tm_mday=17, tm_hour=8, tm_min=36, tm_sec=20, tm_wday=2, tm_yday=107, tm_isdst=0)

In [10]:
time.tzname

('Hora est. Pacífico, Sudamérica', 'Hora verano Pacífico Sudamérica')

In [13]:
time.time()#cuantos segundos pasaron desde el punto de inicio de python

1555508390.8787048

Operaciones con tiempo

In [18]:
def sumaVectores():
    t1 = time.time()
    x = range(10000000)
    y = range(10000000)
    z = []
    for i in range(len(x)):
        z.append(x[i]+y[i])
    
    return time.time() - t1

In [19]:
sumaVectores()

2.561163902282715

In [20]:
def sumaVerctoresNp():
    t1 = time.time()
    x = np.arange(10000000)
    y = np.arange(10000000)
    
    z = x+y
    return time.time() - t1

In [22]:
sumaVerctoresNp()

0.04487872123718262

In [23]:
type(range(10000000))

range

In [24]:
type(np.arange(10000000))

numpy.ndarray

In [26]:
v = np.array([1,2,3,4])
type(v)

numpy.ndarray

In [30]:
M = np.array([[1,2,3,4],[1,2,3,7]])
type(M)

numpy.ndarray

In [31]:
M.shape

(2, 4)

In [32]:
M.size

8

In [33]:
M.dtype

dtype('int32')

In [34]:
x = np.arange(0,10,2)
x

array([0, 2, 4, 6, 8])

In [53]:
#matriz diagonal
np.diag((1,2,3,4,5,6))

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [36]:
np.ones((10,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
np.random.random_integers(1,10)

C:\Users\laboratorioesan\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  """Entry point for launching an IPython kernel.


7

In [47]:
R = np.random.random((3,3))

In [48]:
R

array([[0.04662459, 0.44120655, 0.44920302],
       [0.67493534, 0.36506966, 0.34267341],
       [0.88618604, 0.0021288 , 0.9030757 ]])

In [49]:
R[1,:]

array([0.67493534, 0.36506966, 0.34267341])

In [50]:
R[1,:2]

array([0.67493534, 0.36506966])

In [51]:
R[1:3,0:2]

array([[0.67493534, 0.36506966],
       [0.88618604, 0.0021288 ]])