## <center>Aprendiendo Python</center>

Este es el primer script de la clase de Inteligencia Artificial Avanzada

### Primera Parte

In [126]:
#print("Hola Mundo")
#x=20
print("Hola")
print(num)

Hola
0


In [125]:
print("Hola Clase")
num = 0

Hola Clase


In [5]:
print("Hola ESAN")

Hola ESAN


## Segunda Parte (Tipos de Datos)

In [2]:
num = -20.98

In [3]:
type(num)

float

In [4]:
cad = 'Hola'
type(cad)

str

In [5]:
bl = True
blf = False
type(blf)

bool

In [10]:
val = 10

In [11]:
type(val)

int

In [12]:
val % 3

1

In [18]:
(cad+' ')*10

'Hola Hola Hola Hola Hola Hola Hola Hola Hola Hola '

In [21]:
print('Hola'+('\n')*5+'Mundo')

Hola




Mundo


In [26]:
print('Hola'+('\t_')*5+'Mundo')

Hola	_	_	_	_	_Mundo


## Listas

In [33]:
lista = [1,2,3,4,'Hola',-2.8,True,'@',[1,'a']]

In [40]:
type(lista[8][0])

int

In [41]:
lista.append(9)

In [42]:
lista

[1, 2, 3, 4, 'Hola', -2.8, True, '@', [1, 'a'], 9]

In [43]:
lista.insert(0,'a')

In [44]:
lista

['a', 1, 2, 3, 4, 'Hola', -2.8, True, '@', [1, 'a'], 9]

In [53]:
lista.count(3)

1

In [54]:
len(lista)

11

In [57]:
lista[-3]

'@'

In [58]:
lista

['a', 1, 2, 3, 4, 'Hola', -2.8, True, '@', [1, 'a'], 9]

In [62]:
lista[-4:]

[True, '@', [1, 'a'], 9]

In [64]:
lista[:3] + lista[3:7]

['a', 1, 2, 3, 4, 'Hola', -2.8]

In [65]:
elemento1 = lista[-2]
elemento1

[1, 'a']

In [67]:
lista.extend(elemento1)
lista

['a', 1, 2, 3, 4, 'Hola', -2.8, True, '@', [1, 'a'], 9, [1, 'a'], 1, 'a']

In [68]:
lista.reverse()

In [69]:
lista

['a', 1, [1, 'a'], 9, [1, 'a'], '@', True, -2.8, 'Hola', 4, 3, 2, 1, 'a']

In [70]:
lista.remove('@')
lista

['a', 1, [1, 'a'], 9, [1, 'a'], True, -2.8, 'Hola', 4, 3, 2, 1, 'a']

In [71]:
lista.remove('a')

## Estructuras Selectivas

In [116]:
if (val > 18):
    print("Eres mayor de edad, tu edad es: "+str(val))
    val=10
elif (val>15):
    print("Ya casi eres mayor de edad, tu edad es: "+str(val))
    val = 30
else:
    print("Eres menor de edad, tu edad es: "+str(val))
    val=16

Ya casi eres mayor de edad, tu edad es: 16


## Estructuras Repetitivas

In [119]:
val =10
while(val > 0):
    print(val)
    val-=1

10
9
8
7
6
5
4
3
2
1


In [120]:
for x in lista[0:5]:
    print(x)

1
[1, 'a']
9
[1, 'a']
True


In [127]:
for i in range(10,100,10):
    print(i)

10
20
30
40
50
60
70
80
90


In [129]:
for i in range(0,len(lista),2):
    print(lista[i])

1
9
True
Hola
3
1


## Diccionarios

In [138]:
diccionario = {1:'Hola',1:'Mundo', 'Hola':-8,'a':[1,2,3]}
diccionario

{1: 'Mundo', 'Hola': -8, 'a': [1, 2, 3]}

In [139]:
diccionario[1]

'Mundo'

In [143]:
diccionario.keys()

dict_keys([1, 'Hola', 'a'])

In [144]:
diccionario.values()

dict_values(['Mundo', -8, [1, 2, 3]])

In [154]:
diccionario2 = {'Juan':[20,44444444],'Carlos':[25,12345678],'Maria':{'edad':10,'dni':1234569}} 

In [155]:
diccionario2['Maria']['dni']

1234569

In [164]:
lista_ord = [-5,3,100,2]
lista_ord.sort()
lista_ord

[-5, 2, 3, 100]

In [166]:
diccionario3 = {'Juan':20,'Maria':20,'Pepe':30}
diccionario3

{'Juan': 20, 'Maria': 20, 'Pepe': 30}

## Archivos

In [180]:
f = open('test.jun','w')

In [170]:
lista_ord

[-5, 2, 3, 100]

In [181]:
for i in lista_ord:
    f.write(str(i)+'\n')

In [182]:
f.write("Junior Fabian")

13

In [183]:
f.close()

In [184]:
f = open('test.jun','r')

In [185]:
lista_lineas = f.readlines()

In [186]:
lista_lineas

['-5\n', '2\n', '3\n', '100\n', 'Junior Fabian']

In [179]:
f.close()

## Funciones

In [1]:
def sumarDosNumeros(num1, num2):
    suma = num1 + num2
    return suma

In [3]:
def sumarDosNumeros2(num1, num2):
    return num1+num2

In [5]:
def cuadrado_cubo(num):
    cuadrado = num**2
    cubo = num**3
    return cuadrado,cubo

In [4]:
sumarDosNumeros2(10,-8)

2

In [7]:
var1 , var2 = cuadrado_cubo(5)

In [9]:
var2

125

In [16]:
def leerArch(nombreArch):
    f = open(nombreArch,'r',encoding='utf-8')
    lineas = f.readlines()
    f.close()
    return lineas

In [18]:
lista_lineas =  leerArch('noticia.txt')

In [28]:
lista_lineas[-1].split()

['Noticia', 'en', 'desarrollo...']

In [37]:
l = "Hola Mundo".split()

In [38]:
" ".join(l)

'Hola Mundo'

### Ejercicios 

1. Función para Leer archivo y retornar una lista con las palabras que tengan más de 2 caracteres

2. Implementar una función recursiva para generar la secuencia de Fibbonaci

# Librerías

In [39]:
import os

In [40]:
os.getcwd()

'C:\\Users\\laboratorioesan'

In [46]:
os.listdir()

['.anaconda',
 '.conda',
 '.condarc',
 '.dnx',
 '.FlashPrint',
 '.freemind',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.keras',
 '.matplotlib',
 '.spss',
 '.spyder-py3',
 '.VirtualBox',
 '.vscode',
 '3D Objects',
 'AppData',
 'Application Data',
 'Clasificacion4Clases.ipynb',
 'Configuración local',
 'Contacts',
 'Cookies',
 'Datos de programa',
 'Desktop',
 'Documents',
 'Downloads',
 'Entorno de red',
 'Favorites',
 'Impresoras',
 'Links',
 'Menú Inicio',
 'MicrosoftEdgeBackups',
 'Mis documentos',
 'Music',
 'My Things',
 'noticia.txt',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{8ebe95f7-3dcb-11e8-a9d9-7cfe90913f50}.TM.blf',
 'NTUSER.DAT{8ebe95f7-3dcb-11e8-a9d9-7cfe90913f50}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{8ebe95f7-3dcb-11e8-a9d9-7cfe90913f50}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'ntuser.pol',
 'OneDrive',
 'pesos',
 'Pictures',
 'Plantillas',
 'PrimerScript.ipynb',
 'Reciente',
 'Saved Games',
 'S

In [47]:
os.mkdir("Test")

In [48]:
os.rmdir("Test")

In [49]:
os.remove("noticia.txt")

### Ejercicios 

3. Crear un directorio con el nombre IA, y generar 50 carpetas dentro de ese directorio con los nombres 1, 2, 3, 4,...,50. Para cada carpeta creada, crear un archivo (TXT) dentro de la carpeta con el nombre de la misma carpeta. El archivo debe contener la frase: "Inteligencia Artificial Avanzada " + nombre del archivo:

"Inteligencia Artificial Avanzada 1"

In [51]:
import numpy as np

In [52]:
import time

In [ ]:
time.sleep()

In [55]:
time.localtime()

time.struct_time(tm_year=2019, tm_mon=4, tm_mday=17, tm_hour=8, tm_min=36, tm_sec=16, tm_wday=2, tm_yday=107, tm_isdst=0)

In [59]:
time.tzname

('Hora est. Pacífico, Sudamérica', 'Hora verano Pacífico Sudamérica')

In [83]:
time.time()

1555508357.3497171

In [86]:
def sumaVectores():
    
    t1 = time.time()
    X = range(10000000)
    Y = range(10000000)
    
    Z = []
    
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    
    return time.time() - t1
        

In [87]:
sumaVectores()

2.563154697418213

In [89]:
def sumaVectores_Numpy():
    
    t1 = time.time()
    
    X = np.arange(10000000)
    Y = np.arange(10000000)
    
    Z = X + Y
    
    return time.time() - t1

In [90]:
sumaVectores_Numpy()

0.045876264572143555

In [99]:
V = np.array([1,2,3,4])
type(V)
V

array([1, 2, 3, 4])

In [100]:
M = np.array([[1,2],[3,4]])
type(M)
M

array([[1, 2],
       [3, 4]])

In [101]:
M.shape

(2, 2)

In [102]:
M.size

4

In [103]:
M.dtype

dtype('int32')

In [106]:
x = np.arange(0,100,10)
x

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [107]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [108]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [109]:
np.ones((10,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [124]:
R = np.random.rand(3,3)

In [117]:
np.ones((10,4)) * 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [123]:
M

array([[1, 2],
       [3, 4]])

In [125]:
M[1,1]

4

In [126]:
R

array([[0.06049406, 0.15103459, 0.31845471],
       [0.62590331, 0.20030133, 0.77679412],
       [0.84481685, 0.74924763, 0.08763914]])

In [133]:
R[1:3,0:2]

array([[0.62590331, 0.20030133],
       [0.84481685, 0.74924763]])

In [ ]:
R[]

### Ejercicios 

4. Realizar una función que reciba un matriz (numpy), y las posiciones  X,Y. 
Retornar una submatriz de esa matriz en función a las posiciones 