# Leer Datos

In [1]:
import pandas as pd
import numpy as np

In [105]:
data = pd.read_csv("datos_LinearRegression.csv",delimiter=";")
data.head(5)

Y    X1     X2    X3  Unnamed: 4  Unnamed: 5  Unnamed: 6
0  250.0  76.0   80.0  13.5         NaN         NaN         NaN
1  220.0  61.0   72.0  12.1         NaN         NaN         NaN
2  200.0  50.0   70.0  11.6         NaN         NaN         NaN
3  350.0  94.0  122.0  12.5         NaN         NaN         NaN
4  210.0  55.0   75.0  13.5         NaN         NaN         NaN

In [106]:
data.isnull().sum()

Y             13
X1            13
X2            13
X3            13
Unnamed: 4    21
Unnamed: 5    21
Unnamed: 6    21
dtype: int64

In [107]:
data = data.iloc[:,0:4]
data.dropna(how="all",axis=0, inplace=True)
data.head()

Y    X1     X2    X3
0  250.0  76.0   80.0  13.5
1  220.0  61.0   72.0  12.1
2  200.0  50.0   70.0  11.6
3  350.0  94.0  122.0  12.5
4  210.0  55.0   75.0  13.5

In [108]:
data.isna().sum()

Y     0
X1    0
X2    0
X3    0
dtype: int64

# Regresion Lineal - Paso a Paso

In [135]:
xi = np.array(data.iloc[:,1:].values)
y = np.array(data.iloc[:,:1].values)
print(x.dtype)
print(y.dtype)

float64
float64


In [110]:
x = np.ones((8,1))
x = np.append(x,xi,1)#add new ones column
x

array([[  1. ,  76. ,  80. ,  13.5],
       [  1. ,  61. ,  72. ,  12.1],
       [  1. ,  50. ,  70. ,  11.6],
       [  1. ,  94. , 122. ,  12.5],
       [  1. ,  55. ,  75. ,  13.5],
       [  1. ,  61. ,  95. ,  14. ],
       [  1. ,  80. , 120. ,  12.5],
       [  1. ,  52. ,  68. ,  14.5]])

In [111]:
xt = np.matrix.transpose(x)#transpuesta
xt

array([[  1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ],
       [ 76. ,  61. ,  50. ,  94. ,  55. ,  61. ,  80. ,  52. ],
       [ 80. ,  72. ,  70. , 122. ,  75. ,  95. , 120. ,  68. ],
       [ 13.5,  12.1,  11.6,  12.5,  13.5,  14. ,  12.5,  14.5]])

In [112]:
XtX = np.matmul(xt,x)#multiplicación
XtX

array([[8.00000e+00, 5.29000e+02, 7.02000e+02, 1.04200e+02],
       [5.29000e+02, 3.66830e+04, 4.84960e+04, 6.86960e+03],
       [7.02000e+02, 4.84960e+04, 6.50420e+04, 9.11670e+03],
       [1.04200e+02, 6.86960e+03, 9.11670e+03, 1.36422e+03]])

In [113]:
inverse = np.linalg.inv(XtX)
inverse

array([[ 3.10721260e+01, -4.94025151e-02, -1.16605171e-02,
        -2.04661607e+00],
       [-4.94025151e-02,  2.23514376e-03, -1.33711555e-03,
         1.45378298e-03],
       [-1.16605171e-02, -1.33711555e-03,  1.09940893e-03,
         2.76710124e-04],
       [-2.04661607e+00,  1.45378298e-03,  2.76710124e-04,
         1.47885095e-01]])

In [114]:
XtY = np.matmul(xt,y)#multiplicacion xt * y
XtY

array([[  1910. ],
       [132055. ],
       [174885. ],
       [ 24754.5]])

In [115]:
w = np.matmul(inverse,XtY)
w

array([[121.70448779],
       [  2.94932354],
       [  0.27556962],
       [ -7.84335821]])

In [116]:
-7.84335821*6 + 0.27556962*2 + 2.94932354*2 + 121.70448779

81.09412485

# Regresion en una función

In [132]:
def regresionLineal(x,y):
    x1 = np.ones((len(x),1))
    x = np.append(x1,x,1)#add ones matriz axis 0
    xt = np.matrix.transpose(x)#transpuesta
    w = []
    w = np.matmul(np.linalg.inv(np.matmul(xt,x)),np.matmul(xt,y))
    return np.concatenate(w)

In [133]:
def predecir(model,X):
    resul = 0
    i=0
    for w in model:
        if i==0:
            resul = resul + w
        else:
            resul = resul + w*X[i-1]
        i=i+1
    return resul

**Modelo**

In [136]:
modelo = regresionLineal(xi,y)
modelo
#[w0,w1,w2,w3,...,wn]

array([121.70448779,   2.94932354,   0.27556962,  -7.84335821])

**Prediccion**

In [137]:
xx = [2,2,6]#x1,x2,x3,...
y = predecir(modelo,xx)
y

81.09412486986571

In [6]:
xi = np.array([[4.0,1.5],
               [3.0,2.2],
               [1.6,1.0],
               [1.2,2.0],
               [3.4,0.8],
               [4.8,1.6]])
y = np.array([[160],[112],[69],[90],[123],[186]])

In [8]:
xi

array([[4. , 1.5],
       [3. , 2.2],
       [1.6, 1. ],
       [1.2, 2. ],
       [3.4, 0.8],
       [4.8, 1.6]])

In [7]:
y

array([[160],
       [112],
       [ 69],
       [ 90],
       [123],
       [186]])

In [10]:
x = np.ones((len(xi),1))
x = np.append(x,xi,1)#add new ones column
x

array([[1. , 4. , 1.5],
       [1. , 3. , 2.2],
       [1. , 1.6, 1. ],
       [1. , 1.2, 2. ],
       [1. , 3.4, 0.8],
       [1. , 4.8, 1.6]])

In [11]:
xt = np.matrix.transpose(x)#transpuesta
xt

array([[1. , 1. , 1. , 1. , 1. , 1. ],
       [4. , 3. , 1.6, 1.2, 3.4, 4.8],
       [1.5, 2.2, 1. , 2. , 0.8, 1.6]])

In [12]:
XtX = np.matmul(xt,x)#multiplicación
XtX

array([[ 6.  , 18.  ,  9.1 ],
       [18.  , 63.6 , 27.  ],
       [ 9.1 , 27.  , 15.29]])

In [13]:
inverse = np.linalg.inv(XtX)
inverse

array([[ 2.85772644, -0.34652768, -1.08888576],
       [-0.34652768,  0.10482697,  0.02112974],
       [-1.08888576,  0.02112974,  0.67615157]])

In [14]:
XtY = np.matmul(xt,y)#multiplicacion xt * y
XtY

array([[ 740. ],
       [2505.4],
       [1131.4]])

In [16]:
w = np.matmul(inverse,XtY)
w

array([[14.56176926],
       [30.10919378],
       [12.16086773]])

In [17]:
14.56176926 +30.10919378*4 + 12.16086773*1.5

153.239845975