# <center><i>Práctica 1 - Python</i></center>

Realice los ejercicios en cada una de las celdas asignadas.
Luego enviar el script (*.ipynb) al correo: <b>jfabian@esan.edu.pe</b>

[3 pts.] <b>Ejercicio 1:</b> 

Escriba una función <b>Func3</b> que tenga como entrada dos números enteros (INICIO,FIN) y que retorne todos los números que son divisibles por 7 pero que no son múltiplos de 5 entre INICIO y FIN (ambos incluídos). En la salida deben aparecer los números separados por comas. 

In [1]:
import numpy as np

In [7]:
def Func1(ini,fin):
    num = []
    for i in range(ini,fin):
        if i % 7 == 0 and i % 5 == 0:
            num.append(i)
    return num

In [8]:
Func1(1000,2000)

[1015,
 1050,
 1085,
 1120,
 1155,
 1190,
 1225,
 1260,
 1295,
 1330,
 1365,
 1400,
 1435,
 1470,
 1505,
 1540,
 1575,
 1610,
 1645,
 1680,
 1715,
 1750,
 1785,
 1820,
 1855,
 1890,
 1925,
 1960,
 1995]

[4 pts.] <b>Ejercicio 2:</b> 

Leer el archivo <b>Email101.txt</b> y reportar la frecuencia de cada una de las palabras.

In [59]:
file = open('Email101.txt','r',encoding='utf-8')
lineas = file.readlines()
file.close()

lineas = " ".join(lineas)#primero unir parrafos
lineas = lineas.split()#separar por palabras
claves = list(set(lineas))
dic = {}

for clave in claves:
    dic[clave] = lineas.count(clave)

dic

{'steps:': 1,
 'closer': 2,
 '24>': 1,
 'against': 1,
 '92,': 2,
 'etc.)': 2,
 'Graphics': 2,
 'itself': 1,
 '3.1>': 1,
 'buying': 1,
 'reliable—method': 1,
 'windows,': 1,
 'receiver': 1,
 'NREN': 1,
 'Web.': 1,
 'onto': 1,
 'behind': 2,
 'can': 129,
 'news.': 1,
 "PDN's.": 1,
 'catalogue.': 1,
 '"hangup"': 1,
 'password': 7,
 'ask,': 1,
 '2.3>': 1,
 'catalogued.': 1,
 'This': 72,
 'once': 6,
 '95,': 1,
 '(CARL).': 1,
 'person,': 1,
 '(case': 1,
 'method': 18,
 '5.': 4,
 'own': 19,
 'brochures': 1,
 'age': 1,
 '"guvax.acc.georgetown.edu:/cpet_projects_in_electronic_text/cpet_user_gu': 1,
 'exchange': 2,
 'needed': 5,
 'site.': 1,
 'Farmer,': 1,
 'peculiarities': 1,
 'Congress.': 1,
 'newsgroups': 3,
 'Science': 3,
 '(1992).': 2,
 'it?': 1,
 'You': 77,
 'feature—and': 1,
 "I've": 1,
 "wouldn't": 1,
 'delay': 1,
 'place': 3,
 'great': 8,
 'indemnify': 1,
 'February': 1,
 '*26': 1,
 'social': 1,
 'DELPHI': 5,
 'owner,': 1,
 'Professor': 1,
 'caveat:': 1,
 'sample': 1,
 'named': 2,
 'appe

[6 pts.] <b>Ejercicio 3:</b> 

En base al archivo <b>Email101.txt</b>, generar un archivo <b>Email102.txt</b> en el cual se realice el siguiente proceso de limpieza:

* Todas las palabras a minúsculas
* Mantener sólo palabras con más de 4 caracteres
* Eliminar dígitos [0-9]

In [68]:
f = open("Email101.txt","r")
lines = f.readlines()
f.close()

f2 = open("Email102.txt","w")

for line in lines:
    selected =[]
    
    for word in line.split():
        if len(word)>4 and word.isalpha(): ## si es una palabra
            selected.append(word.lower())
    
    strg = " ".join(selected)
    
    f2.write(strg+"\n")
    
f2.close()

[3 pts.] <b>Ejercicio 4:</b> 

Usando el archivo <b>Email101.txt</b>, realizar la suma de todas las cantidades que están representado en dólares.

In [69]:
#CODE
import re 

f = open("Email101.txt","r")
lines = f.readlines()
f.close()

strg = " ".join(lines)

lista = []
suma = 0
for w in strg.split():
    if w[0]=='$' and w[1:].isdigit():
        lista.append(w)
        suma = suma + int(w[1:])

print("Monto Total: "+str(suma))
print("Montos: ",lista)

Monto Total: 2601
Montos:  ['$10', '$50', '$100', '$350', '$2000', '$2', '$2', '$4', '$20', '$2', '$2', '$9', '$50']


[4 pts.] <b>Ejercicio 5:</b> 

Implementar una función que reciba 2 matrices numpy ( I , F ), la matriz I de tamaño MxN y la matriz F de tamaño 3x3. La función debe retornar la multiplicación de la matriz de F por cada área de 3x3 de la matriz I.

Tip: Para generar una matriz de tamaño (x,y) usar: 

<code>np.random.randint(255, size=(x, y))</code>

In [25]:
#Ejemplo: Generando una matriz de 3 x 3 con valores máximos 255
import numpy as np
np.random.randint(255, size=(3, 3))

array([[206, 221, 133],
       [179,  88, 217],
       [ 94, 143, 239]])

<img src="https://i.stack.imgur.com/YDusp.png">

In [70]:
#CODE
I = np.random.randint(255, size=(10, 10))
F = np.random.randint(2, size=(3, 3))

In [71]:
I

array([[142,  13,  19, 117,  95,  49,  81,   4,   3, 177],
       [200, 219,  76, 120, 195, 202, 117, 219,  26,  31],
       [  4, 138,  58, 110, 250, 172, 161, 115, 186, 234],
       [103, 246, 166,  86, 122,  19, 130, 239, 171, 128],
       [ 66, 106, 115, 121,  33, 117, 169, 244, 190, 170],
       [ 93,  82,  34,  49,  88, 214, 204, 225,  24,  33],
       [109, 164,  30, 143, 207, 102, 232, 240,  93, 148],
       [216, 222, 224, 193, 196, 216,  87, 109, 117, 120],
       [243, 156, 201,  37, 232, 147, 179, 175,  22, 213],
       [117, 191,   9, 188, 143,  31, 139,  20,   1, 106]])

In [72]:
F

array([[0, 1, 1],
       [0, 1, 0],
       [1, 1, 1]])

In [73]:
#CODE
n,m = I.shape

new_matrix=np.zeros((n,m))

for fila in range(1,n-1):
    
    for columna in range(1,m-1):
    
        matriz=I[fila-1:fila+2,columna-1:columna+2]*F
        
        new_matrix[fila,columna]=np.sum(matriz)
        
print(new_matrix)

[[   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.  451.  518.  750.  871.  915.  650.  688.  741.    0.]
 [   0.  948.  752.  799.  874.  762.  885.  900.  781.    0.]
 [   0.  729.  676.  715.  815.  671.  936. 1143. 1195.    0.]
 [   0.  727.  532.  500.  525.  772. 1181. 1107.  771.    0.]
 [   0.  606.  607.  583.  690. 1041. 1191. 1224.  865.    0.]
 [   0.  942.  752.  893. 1114. 1019. 1073.  802.  496.    0.]
 [   0. 1016.  791. 1013.  921. 1108. 1060.  818.  768.    0.]
 [   0.  919. 1006.  766. 1006.  763.  565.  561.  386.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]]


In [74]:
tam = int(input('ingreso el tamaño del diccionario'))
dic = {}
for i in range(0,tam):
    key = input('ingrese la clave ' + str(i))
    concep = input('ingrese concepto ' + str(i))
    dic[key] = concep

ingreso el tamaño del diccionario4
ingrese la clave 0nombre
ingrese concepto 0Noe
ingrese la clave 1apellidos
ingrese concepto 1Melo
ingrese la clave 2cursos
ingrese concepto 2Web
ingrese la clave 3ciclo
ingrese concepto 3ix


In [75]:
dic

{'nombre': 'Noe', 'apellidos': 'Melo', 'cursos': 'Web', 'ciclo': 'ix'}

In [81]:
dic.keys is in 'nombre'

SyntaxError: invalid syntax (<ipython-input-81-f9251eca0a41>, line 1)